ls:
  # Regex for dotfiles
  .dir: kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  # Regex for dotfiles
  .js: camelCase | PascalCase | kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  .config.js: kebab-case
  .config.ts: kebab-case
  # Regex for thingsLikeTHISYouKnow (ex: URL, SSG, ...)
  .ts: camelCase | PascalCase | regex:[a-zA-Z]+([A-Za-z]+)+$
  .d.ts: kebab-case
  # Regex for dotfiles
  .yml: kebab-case | regex:^\/?(?:\w+\/)*(\.[\w-]+)
  .md: kebab-case | SCREAMING_SNAKE_CASE
  .json: kebab-case

  .github:
    .dir: lowercase | SCREAMING_SNAKE_CASE

ignore:
  - .git
  - .husky
  - .idea
  - node_modules
  - apps/web/dist
  - apps/web/node_modules
  - docs/_config.yml
  - packages/clients/cms/node_modules
  - packages/config/eslint/node_modules
  - packages/config/stylelint/node_modules
  - packages/config/tsconfig/node_modules
